display:
background_image: https://tetacourse.com/uploads/posts/2020-07/1595211523_1.jpg
jobs:
- name: lab-prep
  plan:
  - get: git-resource
    trigger: true
  - config:
      image_resource:
        name: ""
        source:
          repository: sconrod/python-aws-image
          tag: 2
        type: docker-image
      inputs:
      - name: git-resource
      platform: linux
      run:
        path: sh
        args:
          - -ce
          - |
            export AWS_PAGER=""
            export Name=$NAME
            echo $NAME
            aws configure set aws_access_key_id $AWS_KEY_ID
            aws configure set aws_secret_access_key $AWS_KEY
            aws configure set default.region $REGION

            echo "WELCOME TO THE CISCO FSO API LAB FOR DEVOPS/NETOPS ENGINEERS"

    task: check-aws
    params:
      VAULT_ADDR: http://prod-vault.devops-ontap.com:8200
      SSH_TOKEN: ((ssh-token.token))

resource_types:
resources:
  - name: git-resource
    source:
      Username: ((Username))
      branch: ((git-branch))
      email: ((email))
      private_key: ((private_key))
      uri: ((git-uri))
    type: git