---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/sdwan-ubuntu
    tag: 1.0

inputs:
  - name: git-resource

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  REGION: us-west-2
  NAME: us-west-2a
  VAULT_ADDR: http://prod-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      echo "Deploying vbond CONTROLLER: Your Orchestration Management System. All SD-WAN Appliances first authenticate and authorize here using certificate and serial or on virtual devices an OTP"
      export AWS_PAGER=""
      export Name=$NAME
      echo $NAME
      aws configure set aws_access_key_id $AWS_KEY_ID
      aws configure set aws_secret_access_key $AWS_KEY
      aws configure set default.region $REGION

      chmod a+x git-resource/tasks/cluster/aws_deploy_vbond_cluster/input/aws_vbond_vbond_2.sh
      ./git-resource/tasks/cluster/aws_deploy_vbond_cluster/input/aws_vbond_vbond_2.sh

      